name: flutter_application_1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  http: ^0.13.5
  lottie: ^1.4.3
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  intl: ^0.17.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/kelas/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 500
